---
- name: Ensure database is created
  postgresql_db:
    name: "{{ pretix_db_name }}"

- name: Create database user and ensure the user access to the database
  postgresql_user:
    db: "{{ pretix_db_name }}"
    name: "{{ pretix_db_user }}"
    priv: ALL

- name: Ensure user does not have unnecessary privileges
  postgresql_user:
    name: "{{ pretix_db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
