---
- name: Install required apt packages
  apt:
    name:
      - git
      - build-essential
      - python-dev
      - python3-venv
      - python3
      - python3-pip
      - python3-dev
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - zlib1g-dev
      - libssl-dev
      - gettext
      - libpq-dev
      - libmariadbclient-dev
      - libjpeg-dev
      - libopenjp2-7-dev

- name: Create group
  group:
    name: '{{ pretix_group }}'
    state: present

- name: Create user
  user:
    name: '{{ pretix_user }}'
    group: '{{ pretix_group }}'
    state: present

- name: Prepare directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ pretix_user }}'
    group: '{{ pretix_group }}'
  loop:
    - '{{ pretix_config_dir }}'
    - '{{ pretix_dir }}/data/media'

- name:  Create config file
  template:
    src: pretix.cfg.j2
    dest: '{{ pretix_config_dir }}/pretix.cfg'
    owner: '{{ pretix_user }}'
    group: '{{ pretix_group }}'
    mode: 0600

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Install python dependencies
  become: true
  become_user: '{{ pretix_user }}'
  pip:
    virtualenv: '{{ pretix_dir }}/venv'
    name:
      - setuptools
      - wheel
      - pretix[postgres]
      - gunicorn

- name: Instll specific version of urllib
  become: true
  become_user: '{{ pretix_user }}'
  pip:
    virtualenv: '{{ pretix_dir }}/venv'
    name:
      - urllib3==1.24
